<?php
/**
 * This file is part of the DTO Generator Bundle.
 *
 * (c) HellFirePvP <dev.hellfire@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace HellFirePvP\Bundle\DTOGeneratorBundle\DTO\Generator;

use ReflectionClass;
use UnexpectedValueException;

/**
 * Creates DTO class files with validations and types derived from the class the DTO is for.
 *
 * Takes inspiration from Doctrine's ProxyGenerator.
 *
 * @author HellFirePvP <dev.hellfire@gmail.com>
 */
class DTOClassGenerator
{
    /**
     * The directory the DTOs are saved into.
     *
     * @var string
     */
    protected string $dtoDirectory;

    /**
     * The Namespace DTOs are organized into.
     *
     * @var string
     */
    protected string $dtoNamespace;

    /**
     * Base Template used to generate DTO classes.
     *
     * @var string
     */
    protected string $dtoClassTemplate = '<?php

namespace <namespace>;

/**
 * THIS FILE WAS GENERATED BY THE DTO GENERATOR.
 * DO NOT EDIT THIS FILE.
 */
class <simpleClassName> extends \<fullDTOClassName>
{

<attributes> 

    /**
     * {@inheritDoc}
     */
    public function getObjectClass(): string
    {
        return <fullClassName>::class;
    }
}
';

    /**
     * DTOClassGenerator constructor.
     *
     * @param string $dtoDirectory The directory DTOs are generated into.
     * @param string $dtoNamespace The namespace of generated DTOs
     */
    public function __construct(string $dtoDirectory, string $dtoNamespace)
    {
        $this->dtoDirectory = $dtoDirectory;
        $this->dtoNamespace = $dtoNamespace;
    }

    /**
     * Generates the DTO file for this class and writes the result to the specified file.
     *
     * @param ReflectionClass $class
     * @param string $targetFile
     */
    public function generateDTOFile(ReflectionClass $class, string $targetFile)
    {

    }

    /**
     * Stores the given DTO's class code into the given file.
     *
     * @param string $dtoClass
     * @param string $file
     */
    private function storeDTOClass(string $dtoClass, string $file)
    {
        $parentDirectory = dirname($file);
        if (!is_dir($parentDirectory) && (false === @mkdir($parentDirectory, 0775, true))) {
            throw new UnexpectedValueException(sprintf("DTO file directory not writeable: " . $parentDirectory));
        }

        if (!is_writable($parentDirectory)) {
            throw new UnexpectedValueException(sprintf("DTO file directory not writeable: " . $parentDirectory));
        }

        $tmpFileName = $file . '.' . uniqid('', true);

        file_put_contents($tmpFileName, $dtoClass);
        @chmod($tmpFileName, 0664);
        rename($tmpFileName, $file);
    }

    /**
     * Resolve the actual filename of the DTO class file to generate of the given class.
     *
     * @param ReflectionClass $class
     *
     * @return string
     */
    public function getDTOClassFileName(ReflectionClass $class): string
    {
        return rtrim($this->dtoDirectory, DIRECTORY_SEPARATOR) .
            DIRECTORY_SEPARATOR .
            '__DTO__' . str_replace('\\', '_', $class->inNamespace()) . '.php';
    }
}
